### ISSUE TITLE
The organization of the group tables seem random (apart from Actual being first)

### ISSUE THREAD

**Issue by wanderrful** [fparma/fparma-web#5]
edit -- when I go back and look harder I can see that you tried to order it as: infantry + panther, infantry + panther... but even still, it'd be better to at least dedicate 1 row to alpha and its panther team, 1 row to bravo and its panther team, etc.

When the Charlie group was created for this first test event, it really scattered the order of the tables for each group.  For example, the two Panther groups are on complete opposite ends of the table for no apparent reason.

So I think you should create some kind of logic to how the tables are sorted and displayed.

I'd recommend making a row in the outer table dedicated to regular infantry groups and then underneath it, a row dedicated to the special vehicle groups.

Or even better yet:  a good way to do this would be to create one of those organizational charts, with Actual in the top center and then the other groups sorted out below them like a tree graph.

**Comment by WhiteFox08** [comment]
I'm pretty sure that it's just phrasing the sqm for the slots, meaning that the mission maker set these units one after the other in the editor, I could be wrong. It would be cool however to change the group positions on the fly for admins though.

**Comment by Cuel** [comment]
Groups are ordered by the mission SQM file (if uploaded), or how the user defined it when manually creating the event. So regarding operation ranch it up, that's how tinter had them ordered in the sqm file

The display is
Group - Group - Group

---

Group - Group - Group

It could be possible to order them like
Group | Group | Group
Group | Group  | Group
Group | Group | Group

(so horizontal instead of vertical)

However I don't think this would look better.
Changing the order would be possible, not prioritized atm, can look into it in the future. I'd prefer to just have drag/drop when creating the event
