### ISSUE TITLE
Event start time should be localized for each client

### ISSUE THREAD

**Issue by SFAriel** [fparma/fparma-web#7]
I duno if this is doable but it would be neat

**Comment by fippefi** [comment]
It already is. Go to Events tab and press on the 'Show dates as' UTC to Local instead.

**Comment by SFAriel** [comment]
I missed that, thanks. But inside the actual event itself it's still just UTC. I guess this means Cuel already had it mind atleast.

**Comment by Cuel** [comment]
It was yeah, had some issue with a guy who didn't synchronize his time so it wouldn't display correctly. Would you prefer if it was shown in local time at first, and maybe a checkbox to display in UTC / from now? I'd prefer to not clutter the event, which is why it was only available when showing all events

**Comment by SFAriel** [comment]
Imo there's plenty of space to show both local and UTC. If you don't want that then just UTC with optional local time switch is fine.
